### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ibrahimbak** [Tomato6966/distube-music-bot#3]
(node:3876) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
(node:3876) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3876) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Tomato6966** [comment]
1. What did u do?
2. Which branche?
3. Which line?

**Comment by ibrahimbak** [comment]
> 1. What did u do?
> 2. Which branche?
> 3. Which line?

i tried to setup it on repl.it the bot starts but when i try to play any song it keeps showing this error. It does not show any specific line

**Comment by Tomato6966** [comment]
1. Dont user replit
2. Which branche...
3.

**Comment by OmarA32** [comment]
same issue, but only when using "lyrics"

using the latest version branch (only got the lyrics command, and the lyrics embed, the config for the lyrics, the delay function, and the random function) the rest are all from the "improved again" branch, and they all work perfectly

first there was no error, but it tells me that it didn't find any lyrics, then I removed `if(!lyrics || lyrics === null || lyrics === "null") return message.reply("no lyrics found!")` so that I can see what the issue is, in the errors, and I found this

 `UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
(node:2055) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2055) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code`

and I'm sure its not my geniusapi token
thank you in advance!

edit: btw I'm using replit, didn't have any issue so far, only the lyrics command is not working

edit: the code    https://pastebin.com/qcAu6HaP
